### ISSUE TITLE
Monitor

### ISSUE THREAD

**Issue by plasmoduck** [dudik/herbe#20]
How can I select what monitor to display notifcations? I have 2 monitors and I'd like it on monitor 1 but it shows on monitor 2.

**Comment by dudik** [comment]
Right now there's no way, but it should be pretty straightforward to implement. Sadly, I'm still in the middle of a somewhat busy semester and I don't have much free time. I will gladly implement this, but not sooner than 2-3 months from now. I'm really sorry.

**Comment by TAAPArthur** [comment]
I can submit a patch. I would lean towards adding a patch that used the primary monitor's size instead of the default screen dimensions. For help setting the primary monitor see `xrandr`

Rationale:
As far as I'm aware, monitor ids/numbers (and possibly even name depending on your setup) aren't useful for static configurations as they can change on restart/re-plug. Also it seem to be common to in other notification systems.

Let me know if this doesn't work for your use case.

**Comment by MostHated** [comment]
Was this added in? I don't see the option for it in the config.h file. Does it need to be manually added? I have 3 monitors and the notifications show up on the farthest top right of the 3rd monitor. I thought it wasn't working at all, at first.

**Comment by dudik** [comment]
At the moment it still does have to be added manually by applying this patch: https://github.com/dudik/herbe/pull/21.

**Comment by MostHated** [comment]
No worries, I was able to get it figured out not longer after I posted that. I kept trying to use `diff filename 21.diff` until I realized you had to actually use *git* to do the patch, lol. After that, I was good to go. :+1:
