### ISSUE TITLE
Patch to make herbe not appear when the focused window is fullscreen

### ISSUE THREAD

**Issue by heyitscassio** [dudik/herbe#28]
I liked a lot this program,  and i can almost substitute dunst. But the only problem that i have is that it shows when there is a fullscreen window. It wold be nice if when herbe is called and the focused window is a fullscreen window it waits to display the output. 

I don't know c or xlib well enough, but i found a post in the [arch linux forums](https://bbs.archlinux.org/viewtopic.php?id=208655) with a solution to find if the focused window is fullscreen via the `_NET_WM_STATE` property. 

```c
#include <stdio.h>
#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Xlib.h>

int
main()
{
    Atom prop_fullsrceen, prop_type, prop, da;
    char *an;
    Display *dpy;
    int di;
    int status;
    unsigned char *prop_ret = NULL;
    unsigned long dl;
    dpy = XOpenDisplay(NULL);

	Window focused;
	int revert_to;
	XGetInputFocus(dpy, &focused, &revert_to);

    prop_type = XInternAtom(dpy, "_NET_WM_STATE", True);
	prop_fullsrceen = XInternAtom(dpy, "_NET_WM_STATE_FULLSCREEN", True);

    status = XGetWindowProperty(dpy, focused, prop_type, 0L, sizeof (Atom), False,
                                XA_ATOM, &da, &di, &dl, &dl, &prop_ret);

    if (status == Success && prop_ret)
    {
        prop = ((Atom *)prop_ret)[0];

        /* Debug output, not really relevant: Re-resolve atom number to
         * printable name */
        an = XGetAtomName(dpy, prop);
        fprintf(stderr, "Type found: %s\n", an);
        if (an)
            XFree(an);

        /* Compare internal atom numbers */
        if (prop == prop_fullsrceen)
            fprintf(stderr, "It's a fullscreen window\n");
    }
	exit(EXIT_SUCCESS);
}
```

If anyone could give me a tip on how to do this i would appreciate it.

Thanks!

**Comment by TAAPArthur** [comment]
@toniz4 Assuming you use an EWMH compliant window manager, then you can read the _NET_ACTIVE_WINDOW property from the root window. And then check that window's state to see if it has the _NET_WM_STATE_FULLSCREEN atom. Once you determined the window is in the fullscreen state, you would then need to listen for property events for the state or active window to change.

General advice/background
- You don't want to use focus directly for various reasons. For example suppose you have your fullscreen window and then open dmenu (or some other program that steals all input focus). In this case, dmenu has input focus but your target window is _NET_ACTIVE property.
- There's the ewmh object that defines these atoms for you and provides some high level wrappers to get them
- _NET_WM_STATE is an array of states. You probably want to iterate over all them to see if any match the FULLSCREEN state
- Once you determined if the active window is fullscreened or not, then you need to wait for property events on the both the root window (to see if the window stops being the active one) and also on the currently fullscreen window (to see if it stops being fullscreen). For an example of how to check the active window and/or listen for property events, I have this [project](https://github.com/TAAPArthur/apples/blob/master/apples.c); it uses xcb but can provide the general idea. Be careful of the case when switching to one fullscreen window to another and also of stopping fullscreen and immediately switching to another fullscreen window.
- An alternative to modding herbe is to have a standalone wrapper than does the fullscreen check. And then having something like `alias herbe=wait_until_not_fullscreen /bin/herbe` in you shell startup file (or making this a script and adding directly to your PATH). This way you could write the check in whatever language/api you want like python or with xcb. Not trying to discourage you from your current course (or using C in general) and you code is close to correct. I just think this is better off as a standalone application rather than a patch to herbe.

**Comment by heyitscassio** [comment]
>I just think this is better off as a standalone application rather than a patch to herbe.

That would be a better idea, thanks for the tips!

**Comment by heyitscassio** [comment]
I was able to make this program, I wasn't able to get the state from the root window, I'm using the focused window. Either way is the same behaviour as dunst. Here is the program:
```c
#include <stdio.h>
#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Xlib.h>

int
main()
{
    Display *dpy;
    XEvent ev;
    dpy = XOpenDisplay(NULL);
	Atom type;
	int format;
	unsigned long nItem, bytesAfter;
	unsigned char *properties = NULL;
	int iItem;
	int isfull;
	Window focused, root;
	int revert_to;

    root = DefaultRootWindow(dpy);
	Atom wmState = XInternAtom(dpy, "_NET_WM_STATE", True);
	Atom wmFull = XInternAtom(dpy, "_NET_WM_STATE_FULLSCREEN", True);


	isfull = 0;
    XSelectInput(dpy, root, SubstructureNotifyMask);
	do {
		isfull = 0;
		XGetInputFocus(dpy, &focused, &revert_to);

		XGetWindowProperty(dpy, focused, wmState, 0, (~0L), False, AnyPropertyType, 
			&type, &format, &nItem, &bytesAfter, &properties);

		for (iItem = 0; iItem < nItem; ++iItem) {
			if (((long *)(properties))[iItem] == wmFull)
				isfull = 1;
		}

		if (isfull) {
			XNextEvent(dpy, &ev);
		}
	} while (isfull);
}
```
If the focused window is fullscreen it will wait for a event and execute the loop again.
Just compile it with `gcc -lX11 getfull.c -o getfull`
